name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release pdf
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf